config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    passwords: 'users/passwords'
  }
  root 'staff#index', :skip => [:registrations]
  get 'change_password', to: 'auth#new'
  post 'change_password', to: 'auth#update_password'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  post 'aws_details_added', to: "integration#aws_details_added"
  post 'integration_data', to: "integration#integration_data"
  # Defines the root path route ("/")
  # root "posts#index"
  resources :staff
  resources :employee
  resources :integration do
    collection do
      get 'google_workspace_callback', to: 'integration#google_workspace_callback'
      get 'microsoft_callback', to: 'integration#microsoft_callback'
      get 'dropbox_callback', to: 'integration#dropbox_callback'
      get 'box_callback', to: 'integration#box_callback'
      get 'authenticate/:integration_id', to: 'integration#authenticate'
      post :slack
    end
    member do 
      get :initiate_slack
    end
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :employee_integrations, dependent: :destroy
  has_many :activity_log, dependent: :destroy
  has_one_attached :image, dependent: :destroy
  accepts_nested_attributes_for :employee_integrations, allow_destroy: true
  validates_uniqueness_of :employee_id, message: "Id can\'t be same"
end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController
    include ActivityLogConcern
    before_action :find_employee, only: %i[show update destroy new edit]
    before_action :find_company_integrations, only: %i[new edit show]
    before_action :add_start_end_date_in_integrations, only: %i[create update]
    before_action :set_service, only: %i[create update destroy]
    
    def index
      @employees = Employee.where(company_id: current_user.company_id)
    end

    def new
      @employee = Employee.new
      intialize_employee_integrations
    end

    def show
    end

    def edit
      intialize_employee_integrations
    end

    def update
      begin
        @employee.update(filtered_employee_params)
        store_activity_log(@employee.id, current_user.id, "updated details")
        filtered_employee_params["employee_integrations_attributes"]&.each do |key, integration|
          if integration["is_integration_deleted"] == "1"
            # assign permission
            assign_remove_permission(integration["integration_id"], filtered_employee_params["name"], filtered_employee_params["email"], @employee[:id],integration["account_type"],integration["is_integration_deleted"],integration["integration_user_id"], filtered_employee_params["secondary_email"])
          elsif integration["is_permission_assigned"] == "1"
            # remove access
            assign_remove_permission(integration["integration_id"], filtered_employee_params["name"], filtered_employee_params["email"], @employee[:id],integration["account_type"],0,nil,filtered_employee_params["secondary_email"])
          end
        end
        redirect_to employee_index_path, notice: 'Employee updated successfully!!', alert: "success"
        # redirect_to edit_employee_path(@employee[:id]), notice: 'Employee updated successfully!!', alert: "success"
      rescue => error
        redirect_to employee_index_path, notice: error.message, alert: "danger"
      end
    end

    # save employee
    def create
      begin
        employee = Employee.new(filtered_employee_params)
        employee.company_id = current_user.company_id;      
        
        if employee.save!
          store_activity_log(employee.id, current_user.id, "Account created")
          filtered_employee_params["employee_integrations_attributes"]&.each do |key, integration|
            if integration["is_permission_assigned"] == "1"
              assign_remove_permission(integration["integration_id"], filtered_employee_params["name"], filtered_employee_params["email"], employee[:id],integration["account_type"],0,nil, filtered_employee_params["secondary_email"])
            end
          end
          redirect_to employee_index_path, notice: 'Employee registered successfully!!', alert: "success"
        else
          redirect_to employee_index_path, notice: 'Something went wrong!!', alert: "danger"
        end
      rescue => error
        if error.message == "SQLite3::ConstraintException: UNIQUE constraint failed: employees.email"
          redirect_to employee_index_path, notice: "Email Already Exists", alert: "danger"
        else
          redirect_to employee_index_path, notice: error.message, alert: "danger"
        end
      end
    end


  # delete employee
  def destroy
    employee_integration = EmployeeIntegration.where(employee_id: @employee.id, integration: 4).first
    if employee_integration.present? && employee_integration.integration_user_id.present?
      @google.delete_workspace_user(@employee.email)
    end
    @employee.destroy;
    redirect_to employee_index_path, notice: 'Employee deleted successfully!!', alert: "success"
  end

    private
    def employee_params
        params.require(:employee).permit(:name, :email, :designation, :phone, :joining_date, :employee_id, :start_date, :end_date, :image, :secondary_email, :employee_integrations_attributes => [
          :id,
          :employee_id,
          :is_permission_assigned,
          :is_integration_deleted,
          :integration_user_id,
          :integration_id,
          :account_type,
          :start_date,
          :end_date
        ])
    end

    def add_start_end_date_in_integrations
      params["employee"]["employee_integrations_attributes"]&.each do |ind, attributes|
        attributes["start_date"] = params["integration_start_date"]
        attributes["end_date"] = params["integration_end_date"]
      end
    end

    def find_employee
      @employee = Employee.find(params[:id]) if params[:id].present?
    end

    def find_company_integrations
      @company_integrations = CompanyIntegration.where(company_id: current_user.company_id)
    end

    def intialize_employee_integrations
      @company_integrations.each do |integration|
        has_integration = @employee.id.present? && @employee.employee_integrations.where(integration_id: integration.integration_id)
        if has_integration.blank?
          @employee.employee_integrations.build(integration_id: integration.integration_id)
        end
      end
    end

    def filtered_employee_params
      if !employee_params["employee_integrations_attributes"].nil?
        filtered_params = employee_params["employee_integrations_attributes"].select { |key, param| param["is_permission_assigned"] == "1" || param["is_integration_deleted"] == "1"  }
        employee_params.merge(employee_integrations_attributes: filtered_params)
      else
        employee_params
      end
    end

    def set_data
      @integrations = Integration.all
      @show_integrations = false
    end

  def set_service
    access_token = nil
    # for microsoft
    microsoft_app_details = AppRegisterationDetail.where(integration_id: 1, company_id: current_user&.company_id).first
    microsoft_integration = current_user.company.company_integration.where(integration_id: 1).first
    @microsoft = Microsoft::new(microsoft_integration.access_token, app_details: microsoft_app_details) if microsoft_integration.present?
    # for aws
    aws_int = current_user.company.company_integration.where(integration_id: 2).first
    @aws = AwsService::new(aws_int.aws_access_key_id, aws_int.aws_secret_access_key, aws_int.aws_region) if aws_int.present?
    # for google workspace
    google_app_details = AppRegisterationDetail.where(integration_id: 4, company_id: current_user&.company_id).first
    google_workspace_int = current_user.company.company_integration.where(integration_id: 4).first
    @google = Googleworkspace.new(google_workspace_int.access_token, google_workspace_int.refresh_token, current_user&.company_id, app_details: google_app_details) if google_workspace_int.present?
    # for quickbooks
    # for drop box
    dropbox_app_details = AppRegisterationDetail.where(integration_id: 6, company_id: current_user&.company_id).first
    dropbox_integration = current_user.company.company_integration.where(integration_id: 6).first
    @dropbox = DropBox::new(dropbox_integration.access_token, company_id: current_user&.company_id, app_details: dropbox_app_details) if dropbox_integration.present?
    #for box
    box_app_details = AppRegisterationDetail.where(integration_id: 8, company_id: current_user&.company_id).first
    box_int = current_user.company.company_integration.where(integration_id: 8).first
    @box = Box.new(box_int.access_token, box_int.refresh_token, current_user&.company_id, app_details: box_app_details) if box_int.present?
    #for slack
    slack_integration = current_user.company.company_integration.where(integration_id: 9).first
    access_token = slack_integration.access_token if slack_integration.present?
    channels = slack_integration.slack_channels.presence || nil  if slack_integration.present?
    @slack = SlackService::new(access_token, channels) if slack_integration.present?
  end

  def update_integration_user_id(employee_id, integration_id, integration_user_id)
    employee_integration = EmployeeIntegration.where(employee_id: employee_id, integration_id: integration_id)
    if employee_integration.present?
      employee_integration.update(integration_user_id: integration_user_id)
    end
  end

  # assign permission based on interations
  def assign_remove_permission(integration_id, name, email, employee_id,account_type, is_integration_deleted, integration_user_id=nil, secondary_email=nil)
    activity_log_msg = "";
    case integration_id.to_s
      when "1"
        if is_integration_deleted == 0
          # invite user on microsoft
          data = nil
          if account_type == "microsoft"
            data = @microsoft.invite_user(email, name, current_user&.company_id,integration_id);
          elsif account_type == "teams"
            data = @microsoft.invite_user_to_teams(email, name, current_user&.company_id,integration_id);
          elsif account_type == "share_point"
            data = @microsoft.invite_user_to_sharepoint_site(email, name, current_user&.company_id,integration_id)
          end
          # store user id from microsoft so we can remove that user or there permission
          if !data
            remove_employee_integration(employee_id, integration_id);
            raise "Something went wrong while assigning Microsoft permission. Please try again"
          end
          update_integration_user_id(employee_id, integration_id,data["invitedUser"]["id"]);
          activity_log_msg = "has added <b>Microsoft Office 365</b> account access."
        else
          # remove access from employee
          if integration_user_id.present?
            if account_type == "microsoft" || account_type == "sharepoint"
              @microsoft.remove_access(integration_user_id,current_user&.company_id,integration_id);
            elsif account_type == "teams"
              @microsoft.delete_team_member(integration_user_id,current_user&.company_id,integration_id);
            end
            @microsoft.remove_access(integration_user_id,current_user&.company_id,integration_id);

app/views/employee/_form.html.erb
<div class="row" id="employeeForm">
  <div class="col-md-4 col-sm-12 mt-2">
    <%= form.label :image, "Image", class: "form-label" %>
    <%= form.file_field :image, class: "form-control", accept: "image/*", placeholder: "Enter name" %>
  </div>
  <div class="col-md-4 col-sm-12 mt-2">
    <%= form.label :name, "Name", class: "form-label" %> <span style="color:red">*</span>
    <%= form.text_field :name, class: "form-control", :required => true, placeholder: "Enter name" %>
  </div>
  <div class="col-md-4 col-sm-12 mt-2">
    <%= form.label :email, "Email", class: "form-label" %><span style="color:red">*</span>
    <%= form.email_field :email, class: "form-control",:required => true, placeholder: "Enter email" %>
  </div>
  <div class="col-md-4 col-sm-12 mt-2">
  </div>
  <div class="col-md-4 col-sm-12 mt-2">
    <%= form.label :designation, "Designation", class: "form-label" %><span style="color:red">*</span>
    <%= form.text_field :designation, class: "form-control",:required => true, placeholder: "Enter designation" %>
  </div>
  <div class="col-md-4 col-sm-12 mt-2">
    <%= form.label :phone, "Phone Number", class: "form-label" %><span style="color:red">*</span>
    <%= form.text_field :phone, class: "form-control",:required => true, placeholder: "Enter phone number" %>
  </div>
  <div class="col-md-4 col-sm-12 mt-2">
  </div>
  <div class="col-md-4 col-sm-12 mt-2">
    <%= form.label :joining_date, "Joining Date", class: "form-label" %><span style="color:red">*</span>
    <%= form.date_field :joining_date, class: "form-control",:required => true, placeholder: "Select joining date" %>
  </div>
  <div class="col-md-4 col-sm-12 mt-2">
    <%= form.label :employee_id, "Employee Id", class: "form-label" %><span style="color:red">*</span>
    <%= form.text_field :employee_id, class: "form-control",:required => true, placeholder: "Enter employee" %>
  </div>
  <div class="col-md-4 col-sm-12 mt-2">
  </div>
  <div class="col-md-4 col-sm-12 mt-2">
    <%= form.label :start_date, "Start Date", class: "form-label" %><span style="color:red">*</span>
    <%= form.date_field :start_date, class: "form-control",:required => true, placeholder: "Select start date" %>
  </div>
  <div class="col-md-4 col-sm-12 mt-2">
    <%= form.label :integration_end_date, "End Date", class: "form-label" %>
    <%= form.date_field :end_date, class: "form-control", placeholder: "Select end date" %>
  </div>
  <div class="col-md-4 col-sm-12 mt-2">
  </div>
  <div class="col-md-4 col-sm-12 mt-2">
    <%= form.label :secondary_email, "Secondary Email", class: "form-label" %>
    <%= form.email_field :secondary_email, class: "form-control", placeholder: "Enter secondary email" %>
  </div>
  <div class="col-md-4 col-sm-12 mt-2">
  </div>
  <p></p>
  <% if @employee.id.present? %>
    <div class="col-md-4 col-sm-12">
      <span>Platforms & Permissions</span>
    </div>
    <%  @employee&.employee_integrations&.each do |employee_int| %>
    <% if !employee_int.id.present? %>
      <% next %>
    <% end %>
    <div class="col-md-2 col-sm-4">
      <div class="mt-2 p-1 d-flex" style="border: 1px solid rgba(0, 0, 0, .125);border-radius:7px;align-items: center;justify-content: center;">
          <%= image_tag employee_int&.integration&.logo, class: "rounded-circle", style: "height: 22px;" %>
          <span><%= employee_int&.integration&.name %></span>
          <%= image_tag "ok.svg", class: "rounded-circle", style: "height: 14px;" %>
      </div>
    </div>
    <% end %>
  <% end %>
  <div class="col-md-12 col-sm-12 d-flex mt-3" style="justify-content:end;align-items:end;">
    <button type="button" onclick="toggleModal()" class="btn btn-primary">Select platform & permission</button>
    <div id="integrationModal" class="modal-container hide-modal">    
      <div class="backdrop"></div>
      <div class="show" id="shareRecipeModal" tabindex="-1" aria-labelledby="newItemRemoteModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content" id="modal_content">
                <div class="modal-header">
                    <h4 class="modal-title" id="newItemRemoteModalLabel">Platforms</h4>
                    <button type="button" class="btn-close" onclick="toggleModal()" aria-label="Close"></button>
                </div>

                <div class="modal-body">
                    <div class="row">
                      <%= form.fields_for :employee_integrations do |f| %>
                          <%= f.hidden_field :integration_user_id, value: f.object.integration_user_id %>
                            <div class="col-md-12 col-sm-12 d-flex justify-content-between">
                                <div class="d-flex p-2">
                                  <%= image_tag f.object.integration&.logo ,class: "rounded-circle", style: "height: 28px;"%>
                                  <div class="d-flex flex-column" style="padding-left: 10px;">
                                      <b><%= f.object.integration&.name %></b>
                                  </div> 
                                  <%= f.hidden_field :integration_id, value: f.object.integration_id %>
                                </div>
                                <div>
                                  <%= f.check_box :is_permission_assigned, value: nil, disabled: f.object.id.present? ? true : false %>
                                </div>
                            </div>
                            <% if f.object.integration_id == 1 %>
                            <div class="roles" style="margin-left:10px;">
                              <div class="row mb-2">
                                <div class="col-md-4 col-sm-4">
                                  <%= f.radio_button :account_type, "microsoft", checked: true  %>
                                  <%= f.label :account_type, "Microsoft", value: "true"  %>
                                </div>
                                <div class="col-md-4 col-sm-4">
                                  <%= f.radio_button :account_type, "teams", checked: f.object.account_type == "teams" ? true : false   %>
                                  <%= f.label :account_type, "Teams", value: "true"  %>
                                </div>
                                <div class="col-md-4 col-sm-4">
                                  <%= f.radio_button :account_type, "share_point", checked: f.object.account_type == "share_point" ? true : false   %>
                                  <%= f.label :account_type, "SharePoint", value: "true"  %>
                                </div>
                              </div>
                            </div>
                            <% elsif f.object.integration_id == 4 %>
                            <div class="roles" style="margin-left:10px;">
                              <div class="row mb-2">
                                <div class="col-md-6 col-sm-6">
                                  <%= f.radio_button :account_type, "google_workspace", checked: true  %>
                                  <%= f.label :account_type, "G Workspace", value: "true"  %>
                                </div>
                                <div class="col-md-6 col-sm-6">
                                  <%= f.radio_button :account_type, "google_cloud", checked: f.object.account_type == "google_cloud" ? true : false %>
                                  <%= f.label :account_type, "G Cloud", value: "false"  %>
                                </div>
                              </div>
                            </div>
                            <% elsif f.object.integration_id == 6 %>
                            <div class="roles" style="margin-left:10px;">
                              <div class="row mb-2">
                                <div class="col-md-6 col-sm-6">
                                  <%= f.radio_button :account_type, "member_only", checked: true  %>
                                  <%= f.label :account_type, "Member", value: "true"  %>
                                </div>
                                <div class="col-md-6 col-sm-6">
                                  <%= f.radio_button :account_type, "team_admin", checked: f.object.account_type == "team_admin" ? true : false %>
                                  <%= f.label :account_type, "Team Admin", value: "false"  %>
                                </div>
                              </div>
                            </div>
                            <% else %>
                            <%= f.hidden_field :account_type, value: "developer" %>
                            <% end %>
                            <% if f.object.employee_id.present? && f.object.id.present? %>
                            <div class="mb-1" style="display: flex;justify-content: end;align-items: end;">
                            <%= f.hidden_field :is_integration_deleted,class: "integration#{f.object.id}" , value: "0" %>
                            <%= image_tag("delete-grey.svg",class: "remove-access",id: "delete-image-grey#{f.object.id}", style: "height: 22.5px;width: 22.5px;display:none;", "data-id": f.object.id )  %>
                            <%= image_tag("delete.svg",class: "remove-access",id: "delete-image#{f.object.id}", style: "height: 22.5px;width: 22.5px;", "data-id": f.object.id )  %>
                            </div>
                            <% end %>
                            <hr>
                      <% end %>
        
                        <div class="col-md-2 col-sm-2 form-group">
                            <label for="start">Start</label>
                        </div>
                        <div class="col-md-4 col-sm-4 form-group">
                            <input type="date" name="integration_start_date" id="" class="form-control">
                        </div>
                        <div class="col-md-2 col-sm-2 form-group">
                            <label for="start">End</label>
                        </div>
                        <div class="col-md-4 col-sm-4 form-group">
                            <input type="date" name="integration_end_date" id="" class="form-control">
                        </div>
                        <div class="col-md-12 col-sm-12 mt-2 mb-2" align="center">
                            <button type="button" class="btn btn-primary" style="width: 34%;" onclick="toggleModal()">Submit</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
function toggleModal() {
  if ($("#integrationModal")[0]?.classList?.contains('hide-modal')) {
    $("#integrationModal")?.removeClass("hide-modal"); 
    $("body")?.addClass("disable-scroll");   
  } else {
    $("#integrationModal")?.addClass("hide-modal"); 
    $("body")?.removeClass("disable-scroll");   
  }

  $(".remove-access").click(e=>{
    let employee_integration_id = $(e.target).attr("data-id");
    console.log(employee_integration_id)
    if(employee_integration_id){
      let value = $(`.integration${employee_integration_id}`).val()
      let is_integration_deleted = value == "0" ? 1 : 0;
      $(`.integration${employee_integration_id}`).val(is_integration_deleted)
      if(is_integration_deleted){
        $(`#delete-image-grey${employee_integration_id}`).css("display","block");
        $(`#delete-image${employee_integration_id}`).css("display","none");
      }else{
        $(`#delete-image${employee_integration_id}`).css("display","block");
        $(`#delete-image-grey${employee_integration_id}`).css("display","none");
      }
    }
  })
}
</script>

app/views/employee/edit.html.erb
<div class="container mt-4">
<%= form_for @employee, :url => employee_path(@employee.id), method: :put do |form| %>
  <div class="row">
    <div class="col-md-6 col-sm-6">
      <h4>Employee</h4>
    </div>
    <div class="col-md-6 col-sm-6 mb-3" style="display: flex;justify-content: right;align-items: center;">
      <%= link_to "Delete", employee_path(@employee.id), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-danger", style: "margin-right: 10px;"  %>
      <%= link_to "Cancel", employee_index_path, data: {turbo_method: :get}, class: "btn btn-warning", style: "margin-right: 10px;" %>
      <button class="btn btn-primary" id="add-staff">Save</button>
    </div>
  </div>
  <div class="card">
    <div class="card-body p-4">
      <h5>Edit Employee</h5>
      <% if alert %>
      <div class="alert alert-<%= alert %>" role="alert">
        <%= notice %>
      </div>
      <% end %>
        <%= render :partial => "form", :object => form %>
    </div>
  </div>
<% end %>
  <div class="card mt-3">
    <div class="card-body p-4">
      <h5 class="mb-4">Activities</h5>
      <% if @employee.present? %>
        <% @employee.activity_log&.each do |activity| %>
          <div class="d-flex">
            <div class="circle" style="background-color: red;height: 14px;width: 14px;border-radius: 7px;"></div>
            <div class="flex-column">
              <div class="date" style="color:grey"><%= activity.created_at.strftime("%I:%M %p") %></div>
              <div class="date"><b><%= activity.user.name %></b> <%= activity.description&.html_safe %></span></div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<script>
  $(document).ready(()=>{
    setTimeout(() => {
     $(".alert").hide();
    }, 3000);
  });
</script>

app/views/employee/index.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-6 col-sm-6">
      <h4>Employee</h4>
      <% if alert %>
        <div class="alert alert-<%= alert %>" role="alert">
          <%= notice %>
        </div>
      <% end %>
  </div>
  <div class="col-md-6 col-sm-6" style="display: flex;justify-content: right;align-items: center;">
    <%= link_to "Add Employee", new_employee_path, data: {turbo_method: :get}, class: "btn  btn-primary" %>
  </div>
  </div>
  <div class="row">
    <% if @employees == nil || @employees.blank? %>
      <h6 class="mt-5 d-flex" style="justify-content:center;align-item:center;">No employees found!!</h6>
    <% else %>
    <% @employees&.each do |employee| %>
      <div class="col-md-4 col-sm-12">
        <div class="card mt-2">
          <div class="card-body">
            <div class="d-flex">
              <%= image_tag employee&.image.present? ? employee&.image : "user.png",class: "rounded-circle", style: "width: 55px;"%>
              <div class="d-flex flex-column">
                <b><%= employee&.name %> </b>
                <span style="color:grey;font-size: 14px;"><%= employee&.designation %></span>
              </div> 
              <div>
                <%= link_to image_tag("user-edit.svg"), edit_employee_path(employee.id), data: {turbo_method: :get} %>
              </div>
            </div>
            <div class="mt-3">
              <span>Emp ID:</span> <span style="color:grey;"><%= employee&.employee_id %></span>
            </div>
            <div class="mt-1">
              <span>Joining Date:</span> <span style="color:grey;"><%= employee&.joining_date.strftime("%d-%b-%Y") %></span>
            </div>
            <div>
              <div class="row">
                <% employee&.employee_integrations&.each do |employee_int| %>
                    <div class="col-md-6 col-sm-6">
                      <div class="mt-2 p-1 d-flex" style="border: 1px solid rgba(0, 0, 0, .125);border-radius:7px;align-items: center;justify-content: center;">
                          <%= image_tag employee_int&.integration&.logo, class: "rounded-circle", style: "height: 22px;" %>
                          <span><%= employee_int&.integration&.name %></span>
                          <%= image_tag "ok.svg", class: "rounded-circle", style: "height: 14px;" %>
                      </div>
                    </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <% end %>
  </div>
</div>
<script>
  setTimeout(() => {
      $(".alert").hide();
    }, 5000);
</script>

app/views/employee/new.html.erb
<div class="container mt-4">
<%= form_for @employee, url: '/employee',id: 'staff-form', method: :post, :html => { :multipart => true } do |form| %>
  <div class="row">
    <div class="col-md-6 col-sm-6">
      <h4>Employee</h4>
    </div>
    <div class="col-md-6 col-sm-6 mb-3" style="display: flex;justify-content: right;align-items: center;">
      <%= link_to "Cancel", employee_index_path, data: {turbo_method: :get}, class: "btn btn-warning", style: "margin-right: 10px;" %>
      <button class="btn btn-primary" id="add-staff">Save</button>
    </div>
  </div>
  <div class="card">
    <div class="card-body p-4">
      <h5>Add Employee</h5>
      <% if alert %>
      <div class="alert alert-<%= alert %>" role="alert">
        <%= notice %>
      </div>
      <% end %>
        <%= render :partial => "form", :object => form %>
    </div>
  </div>
<% end %>
</div>

<script>
  $(document).ready(()=>{
    setTimeout(() => {
     $(".alert").hide();
    }, 3000);
  });
</script>