config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    passwords: 'users/passwords'
  }
  root 'staff#index', :skip => [:registrations]
  get 'change_password', to: 'auth#new'
  post 'change_password', to: 'auth#update_password'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  post 'aws_details_added', to: "integration#aws_details_added"
  post 'integration_data', to: "integration#integration_data"
  # Defines the root path route ("/")
  # root "posts#index"
  resources :staff
  resources :employee
  resources :integration do
    collection do
      get 'google_workspace_callback', to: 'integration#google_workspace_callback'
      get 'microsoft_callback', to: 'integration#microsoft_callback'
      get 'dropbox_callback', to: 'integration#dropbox_callback'
      get 'box_callback', to: 'integration#box_callback'
      get 'authenticate/:integration_id', to: 'integration#authenticate'
      post :slack
    end
    member do 
      get :initiate_slack
    end
  end
end

app/controllers/staff_controller.rb
class StaffController < ApplicationController

  before_action :find_staff, only: %i[show edit update]
  before_action :check_admin

  # show staff page
  def index
    @staff_list = User.where.not(email: current_user.email)
  end

  # show add staff form
  def new
    @roles = Role.all
  end

  # save staff
  def create
    begin
      user = User.new(user_params)
      user.company_id = current_user.company_id;
      user.skip_password_validation = true;
      
      if user.save!
        # send reset password mail
        raw, hashed = Devise.token_generator.generate(User, :reset_password_token)
        user.reset_password_token = hashed
        user.reset_password_sent_at = Time.now.utc
        user.save!
        reset_password_url = Rails.application.routes.url_helpers.edit_user_password_path(reset_password_token: raw)
        UserMailer.welcome_email(user,request.base_url+reset_password_url, false).deliver_now
        redirect_to staff_index_path, notice: 'Staff registered successfully!!', alert: "success"
      else
        redirect_to new_staff_path, notice: 'Something went wrong!!', alert: "danger"
      end
    rescue => error
      redirect_to new_staff_path, notice: error.message, alert: "danger"
    end
  end

  def show
  end

  def edit
    @roles = Role.all
  end

  def update
    begin
      @staff.update(user_params)
      redirect_to staff_index_path, notice: 'Staff updated successfully!!', alert: "success"
    rescue => error
      p error.message
      redirect_to staff_index_path, notice: error.message, alert: "danger"
    end

  end

  # delete staff
  def destroy
    User.destroy_by(id: delete_user_params[:id])
    redirect_to staff_index_path, notice: 'Staff deleted successfully!!', alert: "success"
  end


  private
    def user_params
        params.require(:user).permit(:name, :email, :role_id, :phone, :joining_date)
    end
    def delete_user_params
      params.permit(:id)
    end
    def find_staff
      @staff = User.find(params[:id]) if params[:id].present?
    end
    def check_admin
      if current_user.role&.name != "ADMIN" 
        redirect_to employee_index_path 
      end
    end
end

app/views/staff/_form.html.erb
<div class="row">
  <div class="col-md-6 col-sm-12 mt-2">
    <%= form.label :name, "Name", class: "form-label" %> <span style="color:red">*</span>
    <%= form.text_field :name, class: "form-control", :required => true, placeholder: "Enter your name" %>
  </div>
  <div class="col-md-6 col-sm-12 mt-2">
    <%= form.label :email, "Email", class: "form-label" %><span style="color:red">*</span>
    <%= form.email_field :email, class: "form-control",:required => true, placeholder: "Enter your email" %>
  </div>
  <div class="col-md-6 col-sm-12 mt-2">
    <%= form.label :role_id, "Role", class: "form-label" %><span style="color:red">*</span>
    <%= form.select :role_id, options_for_select(Role.all.map { |role| [role.name, role.id] }, form&.object&.role_id), { include_blank: 'Select a role' }, { class: "form-select" } %>
  </div>
  <div class="col-md-6 col-sm-12 mt-2">
    <%= form.label :phone, "Phone Number", class: "form-label" %><span style="color:red">*</span>
    <%= form.text_field :phone, class: "form-control",:required => true, placeholder: "Enter your phone number" %>
  </div>
  <div class="col-md-6 col-sm-12 mt-2">
    <%= form.label :joining_date, "Joining Date", class: "form-label" %><span style="color:red">*</span>
    <%= form.date_field :joining_date, class: "form-control",:required => true, placeholder: "Select your joining date" %>
  </div>
</div>

app/views/staff/edit.html.erb
<div class="container mt-4">
<%= form_for @staff, :url => staff_path(@staff.id),id: 'staff-form', method: :put do |form| %>
  <div class="row">
    <div class="col-md-6 col-sm-6">
      <h4>Staff</h4>
    </div>
    <div class="col-md-6 col-sm-6 mb-3" style="display: flex;justify-content: right;align-items: center;">
      <%= link_to "Delete", staff_path(@staff.id), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-danger", style: "margin-right: 10px;"  %>
      <%= link_to "Cancel", staff_index_path, data: {turbo_method: :get}, class: "btn btn-warning", style: "margin-right: 10px;" %>
      <button class="btn btn-primary" id="add-staff">Save</button>
    </div>
  </div>
  <div class="card">
    <div class="card-body p-4">
      <h5>Edit Staff</h5>
      <% if alert.present? %>
      <div class="alert alert-<%= alert %>" role="alert">
        <%= notice %>
      </div>
      <% end %>
        <%= render :partial => "form", :object => form %>
    </div>
  </div>
<% end %>
</div>

<script>
  $(document).ready(()=>{
    setTimeout(() => {
      $(".alert").hide();
    }, 3000);
  });
</script>

app/views/staff/index.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-6 col-sm-6">
    <h4>Staff</h4>
  </div>
  <div class="col-md-6 col-sm-6" style="display: flex;justify-content: right;align-items: center;">
    <%= link_to "Add Staff", new_staff_path, data: {turbo_method: :get}, class: "btn  btn-primary" %>
  </div>
  </div>
  <div class="card mt-2">
    <div class="card-body">
      <% if alert %>
      <div class="alert alert-<%= alert %>" role="alert">
        <%= notice %>
      </div>
      <% end %>
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Joining Date</th>
            <th scope="col">Role</th>
            <th scope="col">Phone Number</th>
            <th scope="col">Email Address</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @staff_list.each do |staff| %>
          <tr>
            <td><%= staff.name %></td>
            <td><%= staff.joining_date.strftime("%b %d, %Y") %></td>
            <td><%= staff.role.name %></td>
            <td><%= staff.phone %></td>
            <td><%= staff.email %></td>
            <td class="d-flex">
              <%= link_to "Edit", edit_staff_path(staff.id), data: {turbo_method: :get}, class: "btn btn-primary" %>
              <span>
                <%= link_to "Delete", staff_path(staff.id), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-danger" %>
              </span>
              </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<script>
  setTimeout(() => {
      $(".alert").hide();
    }, 3000);
</script>

app/views/staff/new.html.erb
<div class="container mt-4">
<%= form_for :user, url: '/staff',id: 'staff-form', method: :post do |form| %>
  <div class="row">
    <div class="col-md-6 col-sm-6">
      <h4>Staff</h4>
    </div>
    <div class="col-md-6 col-sm-6 mb-3" style="display: flex;justify-content: right;align-items: center;">
      <%= link_to "Cancel", staff_index_path, data: {turbo_method: :get}, class: "btn btn-warning", style: "margin-right: 10px;" %>
      <button class="btn btn-primary" id="add-staff">Save</button>
    </div>
  </div>
  <div class="card">
    <div class="card-body p-4">
      <h5>Add Staff</h5>
      <% if alert %>
      <div class="alert alert-<%= alert %>" role="alert">
        <%= notice %>
      </div>
      <% end %>
        <%= render :partial => "form", :object => form %>
    </div>
  </div>
<% end %>
</div>

<script>
  $(document).ready(()=>{
    setTimeout(() => {
      $(".alert").hide();
    }, 3000);
  });
</script>