config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    passwords: 'users/passwords'
  }
  root 'staff#index', :skip => [:registrations]
  get 'change_password', to: 'auth#new'
  post 'change_password', to: 'auth#update_password'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  post 'aws_details_added', to: "integration#aws_details_added"
  post 'integration_data', to: "integration#integration_data"
  # Defines the root path route ("/")
  # root "posts#index"
  resources :staff
  resources :employee
  resources :integration do
    collection do
      get 'google_workspace_callback', to: 'integration#google_workspace_callback'
      get 'microsoft_callback', to: 'integration#microsoft_callback'
      get 'dropbox_callback', to: 'integration#dropbox_callback'
      get 'box_callback', to: 'integration#box_callback'
      get 'authenticate/:integration_id', to: 'integration#authenticate'
      post :slack
    end
    member do 
      get :initiate_slack
    end
  end
end

app/models/integration.rb
class Integration < ApplicationRecord
  has_many :company_integration;
  has_many :employee_integration;
  has_many :company, :through => :company_integration
  has_many :employee, :through => :employee_integration
  has_many :app_intergration_details
end

app/controllers/integration_controller.rb
class IntegrationController < ApplicationController
  before_action :set_service, only: %i[authenticate google_workspace_callback microsoft_callback dropbox_callback quickbook_callback box_callback]
  before_action :initialize_slack_integration, only: %i[initiate_slack slack]

  def index
    @integrations = Integration.all
  end

  def initiate_slack

  end

  def slack
    @company_integration['access_token'] =  company_inetgration_params[:access_token]
    @company_integration['slack_channels'] =  company_inetgration_params[:slack_channels]
    @company_integration['refresh_token'] =  ""
    @company_integration.save!
  end

  def google_workspace_callback
    begin
      if params["code"].present?
        data = @google.generate_token_by_code(params["code"]);
        # refresh token only comes at once when the user is authenticated
        add_company_integration(current_user&.company_id,params["state"], data["access_token"], data["refresh_token"]);
        redirect_to integration_index_path	, notice: 'Successfully authenticated with Google.', alert: "success"
      else
        redirect_to integration_index_path, notice: 'Authorization with Google was canceled.', alert: "warning"
      end
    rescue Exception => e
      redirect_to integration_index_path	, notice: "Something went wrong!!", alert: "danger"
    end
  end

  def box_callback
    begin
      if params["code"].present?
        data = @box.generate_token_by_code(params["code"]);
        add_company_integration(current_user&.company_id,params["state"], data["access_token"], data["refresh_token"]);
        redirect_to integration_index_path	, notice: 'Successfully authenticated with Box.', alert: "success"
      else
        redirect_to integration_index_path, notice: 'Authorization with Box was canceled.', alert: "warning"
      end
    rescue Exception => e
      redirect_to integration_index_path	, notice: "Something went wrong!!", alert: "danger"
    end
  end

  def microsoft_callback
    begin
      if params["tenant"].present?
        access_token = @microsoft.generate_token(params["tenant"]);
        add_company_integration(current_user&.company_id,params["state"],access_token,access_token);
        redirect_to integration_index_path	, notice: 'Successfully authenticated with microsoft.', alert: "success"
      else
        redirect_to integration_index_path, notice: 'Authorization with Microsoft was canceled.', alert: "warning"
      end
    rescue Exception => e
      if e.message == "404 Not Found"
        redirect_to integration_index_path
      else
        redirect_to integration_index_path	, notice: "Something went wrong!!", alert: "danger"
      end
    end
  end

  def dropbox_callback
    begin
      if params["code"].present?
        data = @dropbox.generate_token(params["code"])
        add_company_integration(current_user&.company_id,params["state"],data["access_token"],data["refresh_token"]);
        redirect_to integration_index_path	, notice: 'Successfully authenticated with Dropbox.', alert: "success"
    else
      redirect_to integration_index_path, notice: 'Authorization with Google was canceled.', alert: "warning"
      end
    rescue Exception => e
      redirect_to integration_index_path	, notice: "Something went wrong!!", alert: "danger"
    end
    
  end

  def authenticate
    integration_id = params["integration_id"]
    app_details = AppRegisterationDetail.where(integration_id: integration_id, company_id: current_user&.company_id).first
    if app_details.nil? && [2,3,7,9].exclude?(integration_id.to_i)
      @integration_id_value = integration_id
      render :app_registeration_detail and return
    end
    case integration_id.to_s
      when "1"
        # for microsoft
        microsoft_auth_url = @microsoft.authenticate(integration_id)
        redirect_to(microsoft_auth_url,allow_other_host: true)
      when "2"
        # for AWS
        render :aws_detail
        # redirect_to integration_index_path	, notice: "AWS integration not added!!", alert: "danger"
      when "3"
        # for Azure
        redirect_to integration_index_path	, notice: "Azure integration not added!!", alert: "danger"
      when "4"
        # for Google workspace
        google_auth_url = @google.get_google_auth_url(integration_id)
        redirect_to(google_auth_url, allow_other_host: true)
        # redirect_to integration_index_path	, notice: "Google Workspace integration not added!!", alert: "danger"
      when "5"
        # for Quickbooks
        redirect_to integration_index_path	, notice: "Quickbooks integration not added!!", alert: "danger"
      when "6"
        # for Dropbox
        dropbox_auth_url = @dropbox.authenticate(integration_id);
        redirect_to(dropbox_auth_url,allow_other_host: true)
      when "7"
        # for Google Cloud
        # google_auth_url = @google.get_google_auth_url(integration_id)
        # redirect_to(google_auth_url, allow_other_host: true)
        redirect_to integration_index_path	, notice: "Google Cloud integration not added!!", alert: "danger"
      when "8"
        # for Box
        box_auth_url = @box.authenticate(integration_id)
        redirect_to(box_auth_url, allow_other_host: true)
        # redirect_to integration_index_path	, notice: "Box integration not added!!", alert: "danger"
      when "9"
        # for Slack
        redirect_to initiate_slack_integration_path(9)
      else
        redirect_to integration_index_path	, notice: "Please select valid integration!!", alert: "danger" 
    end
  end

  def aws_details_added
    add_company_integration(current_user&.company_id,2,"","",nil, params["aws_access_key_id"], params["aws_secret_access_key"], params["aws_region"]);
    redirect_to integration_index_path	, notice: 'Successfully authenticated with AWS.', alert: "success"
  end

  def integration_data
    app_registeration_detail = AppRegisterationDetail.new(app_resigeration_params.merge(company_id: current_user&.company_id))
    app_registeration_detail.save!
    redirect_to integration_index_path	, notice: 'Now you can Authenticate with App.', alert: "success"
  end

  private
  def company_inetgration_params
    params.require(:company_integration).permit(:access_token, :slack_channels)
  end
  def set_service
    #for Microsoft
    microsoft_app_details = AppRegisterationDetail.where(integration_id: 1, company_id: current_user&.company_id).first
    microsoft_int = current_user.company.company_integration.where(integration_id: 1).first
    @microsoft = Microsoft::new(app_details: microsoft_app_details)
    #for Google
    google_app_details = AppRegisterationDetail.where(integration_id: 4, company_id: current_user&.company_id).first
    google_workspace_int = current_user.company.company_integration.where(integration_id: 4).first
    if google_workspace_int.present?
      access_token = google_workspace_int.access_token
      @google = Googleworkspace.new(access_token, google_workspace_int.refresh_token, company_id: current_user&.company_id, app_details: google_app_details)
    else
      @google = Googleworkspace.new(company_id: current_user&.company_id, app_details: google_app_details)
    end
    # for Dropbox
    drop_box_app_details = AppRegisterationDetail.where(integration_id: 6, company_id: current_user&.company_id).first
    dropbox_integration = current_user.company.company_integration.where(integration_id: 6).first
    if dropbox_integration.present?
      access_token = dropbox_integration.access_token if dropbox_integration.present?
      @dropbox = DropBox::new(access_token, dropbox_integration.company_id, app_details: drop_box_app_details)
    else
      @dropbox = DropBox::new(app_details: drop_box_app_details)
    end
    #for Box
    box_app_details = AppRegisterationDetail.where(integration_id: 8, company_id: current_user&.company_id).first
    p box_app_details
    box_int = current_user.company.company_integration.where(integration_id: 8).first
    if box_int.present?
      access_token = box_int.access_token
      @box = Box.new(access_token, box_int.refresh_token, company_id: box_int.company_id, app_details: box_app_details)
    else
      @box = Box::new(app_details: box_app_details)
    end
  end

  def initialize_slack_integration
    @company_integration = CompanyIntegration.new
    @company_integration[:company_id] = current_user&.company_id;
    @company_integration[:integration_id] = 9;
  end

  def add_company_integration(company_id, integration_id,access_token, refresh_token, quickbook_realm_id=nil, aws_access_key_id=nil, aws_secret_access_id=nil, aws_region=nil)
    company_integration = CompanyIntegration.new
    company_integration[:company_id] = company_id;
    company_integration[:integration_id] = integration_id;
    company_integration[:access_token] = access_token;
    company_integration[:refresh_token] = refresh_token;
    company_integration[:aws_access_key_id] = aws_access_key_id;
    company_integration[:aws_secret_access_key] = aws_secret_access_id;
    company_integration[:aws_region] = aws_region;
    company_integration.save!
  end

  def app_resigeration_params
    params.permit(:client_id, :redirect_uri, :group_id, :client_secret, :tenant_id, :scopes, :integration_id, :company_id)
  end

end

app/views/integration/app_registeration_detail.erb
<div class="container mt-4 px-4">
  <%= form_tag '/integration_data', method: :post, class: 'form' do %>
    <%= hidden_field_tag :integration_id, @integration_id_value %>
    <div class="row align-items-center mb-3">
      <div class="col-6 col-sm-6">
        <h4 class="fw-bold mb-0">AWS Integration</h4>
      </div>
      <div class="col-md-6 col-sm-6 d-flex justify-content-end align-items-center">
        <%= link_to 'Cancel', integration_index_path, class: 'btn btn-outline-info', style: "margin-right: 10px" %>
        <%= submit_tag 'Save', class: 'btn primary-button' %>
      </div>
    </div>
    <div class="card">
      <div class="card-body p-4">
        <h5 class="fw-600">Add AWS Integration</h5>
        <div class="row justify-content-between">
          <div class="col-md-5 col-sm-12 mt-2 pb-2">
            <div class="form-group">
              <%= label_tag 'client_id', 'Client ID', class:'form-label' %> <span style="color:red">*</span>
              <%= text_field_tag 'client_id', nil, required: true, class: 'form-control' %>
            </div>
            <br>
            <div class="form-group">
              <%= label_tag 'redirect_uri', 'Redirect URI', class:'form-label' %> <span style="color:red">*</span>
              <%= text_field_tag 'redirect_uri', nil, required: true, class: 'form-control' %>
            </div>
            <br>
            <div class="form-group">
              <%= label_tag 'group_id', 'Group ID', class:'form-label' %>
              <%= text_field_tag 'group_id', nil, class: 'form-control' %>
            </div>
          </div>
          <div class="col-md-5 col-sm-12 mt-2 pb-2">
            <div class="form-group">
              <%= label_tag 'client_secret', 'Client Secret', class:'form-label' %> <span style="color:red">*</span>
              <%= text_field_tag 'client_secret', nil, required: true, class: 'form-control' %>
            </div>
            <br>
            <div class="form-group">
              <%= label_tag 'tenant_id', 'Tenant ID', class:'form-label' %>
              <%= text_field_tag 'tenant_id', nil, class: 'form-control' %>
            </div>
            <br>
            <div class="form-group">
              <%= label_tag 'scopes', 'Scopes', class:'form-label' %>
              <%= text_field_tag 'scopes', nil, class: 'form-control' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/integration/aws_detail.html.erb
<div class="container mt-4 px-4">
  <%= form_tag '/aws_details_added', method: :post, class: 'form' do %>
    <div class="row align-items-center mb-3">
      <div class="col-6 col-sm-6">
        <h4 class="fw-bold mb-0">AWS Integration</h4>
      </div>
      <div class="col-md-6 col-sm-6 d-flex justify-content-end align-items-center">
        <%= link_to 'Cancel', integration_index_path, class: 'btn btn-outline-info', style: "margin-right: 10px" %>
        <%= submit_tag 'Save', class: 'btn primary-button' %>
      </div>
    </div>
    <div class="card">
      <div class="card-body p-4">
        <h5 class="fw-600">Add AWS Integration</h5>
        <div class="row justify-content-between">
          <div class="col-md-5 col-sm-12 mt-2 pb-2">
            <div class="form-group">
              <%= label_tag 'aws_access_key_id', 'AWS Access Key', class:'form-label' %> <span style="color:red">*</span>
              <%= text_field_tag 'aws_access_key_id', nil, required: true, class: 'form-control' %>
            </div>
            <br>
            <div class="form-group">
              <%= label_tag 'aws_region', 'AWS Region', class:'form-label' %> <span style="color:red">*</span>
              <%= text_field_tag 'aws_region', nil, required: true, class: 'form-control' %>
            </div>
          </div>
          <div class="col-md-5 col-sm-12 mt-2 pb-2">
            <div class="form-group">
              <%= label_tag 'aws_secret_access_key', 'AWS Access Secret', class:'form-label' %> <span style="color:red">*</span>
              <%= text_field_tag 'aws_secret_access_key', nil, required: true, class: 'form-control' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/integration/index.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-12 col-sm-12">
    <h4>Integration</h4>
  </div>
  </div>
  <div class="card mt-2">
    <div class="card-body">
      <% if alert %>
      <div class="alert alert-<%= alert %>" role="alert">
        <%= notice %>
      </div>
      <% end %>
      <% i = 0; %>
      <div class="row">
         <% @integrations.each do |integration| %>
        <% if i%2 == 0 && i != 0 %>
          <hr class="mt-2 mb-2"></hr>
        <% end %>
        <div class="col-md-6 col-sm-6 pt-3 pb-3 d-flex justify-content-between">
          <div class="d-flex p-2">
          <%= image_tag  integration&.logo,class: "rounded-circle", style: "height: 28px;"%>
          <div class="d-flex flex-column" style="padding-left: 10px;">
            <b><%= integration&.name %></b>
            <span style="color:grey;font-size: 14px;"><%= integration&.description %></span>
          </div> 
          </div>
          <div>
            <% if !integration.company_integration.present? && integration.company_integration.size == 0 %>
              <a href="/integration/authenticate/<%= integration&.id %>" class="btn btn-primary" >Connect</a>
            <% else %>
              <button class="btn btn-primary" disabled >Connected</button>
            <% end %>
          </div>
        </div>
        <% i = i+1 %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script>
  setTimeout(() => {
      $(".alert").hide();
    }, 5000);
</script>

app/views/integration/initiate_slack.html.erb
<div class="container mt-4">
    <%= form_for @company_integration, :url => slack_integration_index_path, method: :post  do |f| %>

        <div class="row">
            <div class="col-md-6 col-sm-6">
                <h4>Slack Integration</h4>
            </div>
            <div class="col-md-6 col-sm-6 mb-3" style="display: flex;justify-content: right;align-items: center;">
                <%= link_to "Cancel", staff_index_path, data: {turbo_method: :get}, class: "btn btn-warning", style: "margin-right: 10px;" %>
                <button class="btn btn-primary" id="add-staff">Save</button>
            </div>
        </div>
        <div class="card">
            <div class="card-body p-4">
                <div class="row">
                    <div class="col-md-6 col-sm-12 mt-2">
                        <%= f.label :api_token, "Api Token", class: "form-label" %><span style="color:red">*</span>
                        <%= f.text_field :access_token, class: "form-control",:required => true, placeholder: "Enter Api Token" %>
                    </div>
                    <div class="col-md-6 col-sm-12 mt-2">
                        <%= f.label :channels, class: "form-label" %><br />
                        <%= f.text_field :slack_channels, class: "form-control", autofocus: false, placeholder: "Enter channel name" %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>