config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    passwords: 'users/passwords'
  }
  root 'staff#index', :skip => [:registrations]
  get 'change_password', to: 'auth#new'
  post 'change_password', to: 'auth#update_password'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  post 'aws_details_added', to: "integration#aws_details_added"
  post 'integration_data', to: "integration#integration_data"
  # Defines the root path route ("/")
  # root "posts#index"
  resources :staff
  resources :employee
  resources :integration do
    collection do
      get 'google_workspace_callback', to: 'integration#google_workspace_callback'
      get 'microsoft_callback', to: 'integration#microsoft_callback'
      get 'dropbox_callback', to: 'integration#dropbox_callback'
      get 'box_callback', to: 'integration#box_callback'
      get 'authenticate/:integration_id', to: 'integration#authenticate'
      post :slack
    end
    member do 
      get :initiate_slack
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Entitle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
   <style>
      
  </style>
  </head>

  <body>
<% if current_user.present? %>
  <div class="main-container d-flex">
        <div class="content">
            <nav class="navbar navbar-expand-md navbar-light background-color">
                <div class="header-box px-2 pt-1 pb-1 d-flex justify-content-between">
                    <%= image_tag "logo.svg", style: "margin-left:25px" %>
                </div>
                <div class="container-fluid">
                    <button class="navbar-toggler p-0 border-0" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fal fa-bars"></i>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                        <ul class="navbar-nav mb-2 mb-lg-0">
                            <li class="nav-item d-flex justify-content-between">
                                <div>
                                  <%= image_tag("user.png", class: "rounded-circle", style: "width: 45px;") %>
                                </div>
                                <div style="margin-left:5px">
                                  <b><%= @current_user&.name %></b>
                                  <p style="color:#009D9C"><%= @current_user&.email %></p>
                                </div>
                            </li>

                        </ul>

                    </div>
                </div>
            </nav>
            <div class="d-flex page-content">
                <div class="sidebar background-color" id="side_nav">
                  <ul class="list-unstyled px-2 mt-4">
                      <% if(current_user&.role&.name == "ADMIN") %>
                        <li class="<%= request.fullpath.include?("/staff") || request.fullpath == "/" ? "active" : "" %>">
                        <i class="fal fa-list"></i><%= link_to "Staff", staff_index_path, data: {turbo_method: :get}, class: "text-decoration-none px-3 py-2 d-block" %>
                        </li>
                      <% end %>
                      <li class="<%= request.fullpath.include?("/employee") ? "active" : "" %>">
                      <%= link_to "Employees", employee_index_path, data: {turbo_method: :get}, class: "text-decoration-none px-3 py-2 d-block d-flex justify-content-between" %>
                      </li>
                      <li class="<%=  request.fullpath.include?("/integration") ? "active" : "" %>">
                      <%= link_to "Integration", integration_index_path, data: {turbo_method: :get}, class: "text-decoration-none px-3 py-2 d-block" %>
                      </li>
                      <%# need to change the path once change password flow is setup %>
                      <li class="<%=  request.fullpath.include?("/change_password") ? "active" : "" %>">
                      <%= link_to "Change Password", change_password_path, data: {turbo_method: :get}, class: "text-decoration-none px-3 py-2 d-block" %>

                      </li>
                      <li class="<%=  request.fullpath.include?("/users/sign_out") ? "active" : "" %>">
                      <%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :get}, class: "text-decoration-none px-3 py-2 d-block" %>
                      </li>
                  </ul>
                </div>
              <%= yield %>

            </div>
        </div>
    </div>
<% else %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    <% end %>
    <script>
          $(".sidebar ul li").on('click', function () {
            $(".sidebar ul li.active").removeClass('active');
            $(this).addClass('active');
        });

        $('.open-btn').on('click', function () {
            $('.sidebar').addClass('active');

        });


        $('.close-btn').on('click', function () {
            $('.sidebar').removeClass('active');

        })
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>